// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnulxsjbzsvvatcbjmvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJudWx4c2pienN2dmF0Y2JqbXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzU4MDcsImV4cCI6MjA2NzIxMTgwN30.fKWJXn7ePc6iZOsDN_maC4f1gWzDoWrZpDKHargHSz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});